---
- name: Install Jenkins on devserver
  hosts: devserver
  tasks:
   - name: Install s/w required for Jenkins
     apt:
      name: "{{item.a}}"
      state: present
      update_cache: "{{item.b}}"
     with_items:
      - {a: openjdk-8-jdk,b: yes}
      - {a: git,b: no} 
      - {a: maven,b: no}
   - name: Download Jenkins.war
     get_url:
      url: http://mirrors.jenkins.io/war-stable/latest/jenkins.war
      dest: /home/ubuntu
- name: Setup QA and ProdServers
  hosts: servers
  tasks:
   - name: Install tomcat8 and tomcat-admin
     apt:
      name: "{{item}}"
      state: present
     with_items: 
      - tomcat8
      - tomcat8-admin  
   - name: Copy tomcat-users.xml
     copy:
      src: tomcat_users.xml
      dest: /etc/tomcat8
   - name: Restart tomcat8
     service:
      name: tomcat8
      state: restarted
...
