---
- name: Installing s/w application
  hosts: all
  tasks: 
   - name: install s/w
     apt:
      name: "{{item.a}}"
      state: "{{item.b}}"
      update_cache: "{{item.c}}"
     with_items: 
      - {a: tree,b: present, c: no}
      - {a: apache2,b: absent,c: no}  
      - {a: tomcat8,b: latest,c: yes}  
...

