---
- name: Setup for CI-CD
  hosts: servers
  tasks:
   - name: Install required s/w's like jdk,git,maven,tomcat8
     apt: 
      name: "{{item}}"
      state: present
      update_cache: no
     with_items:
      - openjdk-8-jdk
      - git
      - maven
      - tomcat8
      - tomcat8-admin
- name: Download the code build the code
  hosts: devserver
  tasks:
   - name: Continuous Download
     git:
      repo: https://github.com/intelliqittrainings/maven.git
      dest: /home/ubuntu/git
   - name: Continuous Build
     shell: cd /home/ubuntu/git;mvn package
   - name: Fetch artifact from QAServer into the controller
     fetch:
      src: /home/ubuntu/git/webapp/target/webapp.war
      dest: /tmp
- name: deploy the artifact into QAServer and run the test scripts
  hosts: qaserver
  tasks:
   - name: Continuous Deployment 
     copy:
      src: /tmp/172.31.83.192/home/ubuntu/git/webapp/target/webapp.war
      dest: /var/lib/tomcat8/webapps/testapp.war
   - name: Download the test scripts
     git:
      repo: https://github.com/selenium-saikrishna/FunctionalTesting.git
      dest: /home/ubuntu/test-git
   - name: Continuous Testing
     shell: java -jar /home/ubuntu/test-git/testing.jar  
- name: Deploy the artifact into the prodserver
  hosts: prodserver
  tasks:
   - name: Continuous Delivery
     copy:
      src: /tmp/172.31.83.192/home/ubuntu/git/webapp/target
      dest: /var/lib/tomcat8/webapps/prodapp.war
...

