#
# Installs Tomcat, following best practices of separating CATALINA_BASE directory from CATALINA_HOME
#
---
- name: Tomcat | Install Tomcat
  include: install-tomcat.yml

- name: Tomcat | Prepare Catalina base
  include: prepare-catalina-base.yml

- name: Tomcat | Configure Tomcat for customisation on start-up
  include: configure-tomcat.yml

- name: Tomcat | Copy configuration start-up scripts
  include: configure-startup.yml