---
galaxy_info:
  author: Daniel Rhoades
  description: Tomcat for Ubuntu
  license: MIT
  min_ansible_version: 1.3

  platforms:
      - name: Ubuntu
        versions:
            - precise
            - trusty
      - name: Debian
        versions:
            - wheezy
            - jessie
      - name: EL
        versions:
            - 6
            - 7
  categories:
      - development
      - system
      - web

dependencies: []
  
