machine:
  services:
    - docker

dependencies:
  pre:
    - docker build  -f tests/Dockerfile-ubuntu14.04 -t tomcat_trusty:$CIRCLE_SHA1 .

test:
  post:
    - docker run -d -p 8080:8080 -e WEBAPP_DISTRO_URL=https://github.com/daniel-rhoades/simple-jsf-example/releases/download/v0.1/simple-jsf-example.war tomcat_trusty:$CIRCLE_SHA1; sleep 10
    - curl --retry 10 --retry-delay 5 -v http://localhost:8080/simple-jsf-example