#
# Playbook to test apply the role to the localhost which is expected to be a Docker container
#
- hosts: localhost
  connection: local
  sudo: True
  vars:
      ansible_pkg_mgr: apt
  roles:
    - williamyeh.oracle-java
  tasks:
    - include: 'tasks/main.yml'
  vars_files:
    - 'defaults/main.yml'